version: '3'

services:
  chain0:
    build: .
    volumes:
      - ./disk:/root/disk
      - ./disk/config0:/root/config
    image: chain_test0
    ports:
       - ${JAIL_CLIENT_RPC:-9981}:9981
       - ${JAIL_CHAIN_RPC:-26657}:26657
    command: /root/disk/go_test.sh
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug
      APP_HASH:  $APP_HASH
  chain1:
    build: .
    volumes:
      - ./disk:/root/disk
      - ./disk/config1:/root/config
    image: chain_test1
    command: /root/disk/go_test.sh
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: debug    
      APP_HASH: $APP_HASH
