
---
kind: pipeline
type: exec
name: integration-tests

platform:
  os: linux
  arch: amd64

steps:
- name: integration-tests
  commands:
  - mkdir bin
  - export PATH="$PATH:$PWD/bin"
  - echo "OK"
  - cd integration-tests/jail
  - ./run.sh


