---
kind: pipeline
name: default

steps:
- name: test
  image: ubuntu
  commands:
  - export RUST_BACKTRACE=1
  - export RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
  - export LD_LIBRARY_PATH=$HOME/lib
  - export LIBRARY_PATH=$HOME/lib
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
  - echo "HOME FOLDER = " $HOME
  - cd helloworld
  - ./run.sh

---
kind: pipeline
type: exec
name: integration-tests

platform:
  os: linux
  arch: amd64

steps:
- name: integration-tests
  commands:
  - cd integration-tests/jail
  - ./run.sh

- name: Teardown
  commands:
  - cd integration-tests/jail
  - . ./run_open_port.sh
  - . ./run_test_env.sh
  - docker-compose down
  when:
    status:
     - success
     - failure


