---
kind: pipeline
name: default

steps:
- name: test
  image: chain
  pull: never
  commands:
  - export RUST_BACKTRACE=1
  - export RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
  - export LD_LIBRARY_PATH=$HOME/lib
  - export LIBRARY_PATH=$HOME/lib
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
  - echo "HOME FOLDER = " $HOME

---
kind: pipeline
type: exec
name: integration-tests

platform:
  os: linux
  arch: amd64

steps:
- name: integration-tests
  commands:
  - export NIX_REMOTE=daemon
  - export PATH="$PATH:/nix/var/nix/profiles/default/bin/"
  - . /etc/profile.d/nix.sh 
  - export DOCKER_COMPOSE_PREFIX="${DRONE_BRANCH}"
  - cd integration-tests/jail
  - ./run.sh


