[package]
name = "tx-query-enclave"
version = "0.1.1"
authors = ["Crypto.com <chain@crypto.com>"]
description = "The transaction query enclave."
readme = "../../README.md"
edition = "2018"

[lib]
name = "txqueryenclave"
crate-type = ["staticlib"]

[features]
default = []
sgx-test = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types   = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tstd    = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk.git", features = ["net"] }
sgx_tcrypto = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tse     = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_rand    = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tseal     = { rev = "5b5e512abbbfc3030e8cb274989fb372b685b168", git = "https://github.com/baidu/rust-sgx-sdk" }
parity-scale-codec = { default-features = false, features = ["derive"], version = "1.0" }
chain-core   = { path = "../../../chain-core", default-features = false, features = ["mesalock_sgx"] }
enclave-protocol  = {  path = "../../../enclave-protocol", default-features = false, features = ["mesalock_sgx"] }
enclave-t-common = { path = "../../enclave-t-common" }
secp256k1zkp = { git = "https://github.com/crypto-com/rust-secp256k1-zkp.git", default-features = false, rev = "be445f29a96af31fe079611d26c07f1f596d1c5f", features = ["recovery", "endomorphism", "sgx"] }

[dependencies]
chrono      = { git = "https://github.com/crypto-com/sgx-vendor" }
webpki      = { git = "https://github.com/crypto-com/sgx-vendor" }
base64      = { git = "https://github.com/crypto-com/sgx-vendor" }
yasna       = { git = "https://github.com/crypto-com/sgx-vendor", features = ["bit-vec", "num-bigint", "chrono"] }
num-bigint  = { git = "https://github.com/crypto-com/sgx-vendor" }
bit-vec     = { version = "0.6.1", default-features = false}
httparse    = { version = "1.3.2", default-features = false }
itertools   = { version = "0.8", default-features = false, features = []}
rustls      = { git = "https://github.com/crypto-com/sgx-vendor" }
webpki-roots= { git = "https://github.com/crypto-com/sgx-vendor" }
lazy_static  = { version = "1.4", features = ["spin_no_std"] }
zeroize = { version = "1.0", default-features = false, features = ["zeroize_derive"]}